add color related;use sha1sum to check file change

diff --git a/pctl b/pctl
--- a/pctl
+++ b/pctl
@@ -5,8 +5,29 @@ if [ -z "$rpath" ];then
 fi
 root="$(cd $(dirname $rpath) && pwd)"
 cd "$root"
-RED=$(tput setaf 1)
-RESET=$(tput sgr0)
+red=$(tput setaf 1)
+green=$(tput setaf 2)
+yellow=$(tput setaf 3)
+blue=$(tput setaf 4)
+cyan=$(tput setaf 5)
+reset=$(tput sgr0)
+runAsRoot(){
+    cmd="$@"
+    if [ -z "$cmd" ];then
+        echo "${red}Need cmd${reset}"
+        exit 1
+    fi
+
+    if (($EUID==0));then
+        sh -c "$cmd"
+    else
+        if ! command -v sudo >/dev/null 2>&1;then
+            echo "Need sudo cmd"
+            exit 1
+        fi
+        sudo sh -c "$cmd"
+    fi
+}
 
 user=${SUDO_USER:-$(whoami)}
 home=$(eval echo ~$user)
@@ -56,7 +77,7 @@ add(){
     echo "Enter name local_port upstream [ispac:default 0] [logdir:default /tmp] [id]"
     read name local_port upstream ispac logdir id
     if [ -z $name ] || [ -z $local_port ] || [ -z "$upstream" ];then
-        echo "${RED}Input error.${RESET}"
+        echo "${red}Input error.${reset}"
         exit 1
     fi
     if [ -z $logdir ];then
@@ -67,9 +88,9 @@ add(){
     fi
     mylog "insert data..."
     if [ -z $id ];then
-        sqlite3 "$db" "insert into config(name,local_port,upstream,logdir,ispac) values('$name',$local_port,'$upstream','$logdir',$ispac);" || { echo "${RED}Add failed.${RESET}"; exit 1; }
+        sqlite3 "$db" "insert into config(name,local_port,upstream,logdir,ispac) values('$name',$local_port,'$upstream','$logdir',$ispac);" || { echo "${red}Add failed.${reset}"; exit 1; }
     else
-        sqlite3 "$db" "insert into config(id,name,local_port,upstream,logdir,ispac) values($id,'$name',$local_port,'$upstream','$logdir',$ispac);" || { echo "${RED}Add failed.${RESET}"; exit 1; }
+        sqlite3 "$db" "insert into config(id,name,local_port,upstream,logdir,ispac) values($id,'$name',$local_port,'$upstream','$logdir',$ispac);" || { echo "${red}Add failed.${reset}"; exit 1; }
     fi
 }
 
@@ -180,32 +201,46 @@ status(){
 }
 
 pac(){
+    # editor=vi
+    # if command -v vim >/dev/null 2>&1;then
+    #     editor=vim
+    # fi
+
+    # case $(uname) in
+    #     Linux)
+    #         STAT='stat'
+    #         ;;
+    #     Darwin)
+    #         STAT='stat -x'
+    #         ;;
+    # esac
+    # pacFile=template/pac.action
+    # before="$($STAT $pacFile | grep Modify)" 
+
+    # $editor template/pac.action
+
+    # after="$($STAT $pacFile | grep Modify)" 
+
+    # if [ "$before" != "$after" ];then
+    #     echo "Please ${red}Restart${reset} manually."
+    # else
+    #     echo "pac file not changed."
+    # fi
+
     editor=vi
     if command -v vim >/dev/null 2>&1;then
         editor=vim
     fi
-
-    case $(uname) in
-        Linux)
-            STAT='stat'
-            ;;
-        Darwin)
-            STAT='stat -x'
-            ;;
-    esac
     pacFile=template/pac.action
-    before="$($STAT $pacFile | grep Modify)" 
-
+    sha1sum "${pacFile}" > "${pacFile}.sha1"
     $editor template/pac.action
-
-    after="$($STAT $pacFile | grep Modify)" 
-
-    if [ "$before" != "$after" ];then
-        echo "Please ${RED}Restart${RESET} manually."
+    if ! sha1sum -c --status "${pacFile}.sha1";then
+        echo "${blue}Pac file changed."
+        echo "Restart related service when needed."
     else
-        echo "pac file not changed."
+        echo "${cyan}Pac file not changed."
     fi
-
+    rm "${pacFile}.sha1"
 }
 
 log(){
